const form              = document.getElementById("mediaForm");
const titleInput        = document.getElementById("titleInput");
const typeSelect        = document.getElementById("typeSelect");
const subTypeSelect     = document.getElementById("subTypeSelect");
const statusSelect      = document.getElementById("statusSelect");
const ratingInput       = document.getElementById("ratingInput");
const notesInput        = document.getElementById("notesInput");
const genresContainer   = document.getElementById("genreCheckboxes"); // parent div for genre checkboxes
const stayOnPageToggle  = document.getElementById("stayOnPageToggle");
const saveBtn           = document.getElementById("saveBtn");
const cancelBtn         = document.getElementById("cancelBtn");
const formTitle         = document.getElementById("formTitle");
const msg               = document.getElementById("formMsg");
const stayCheckboxContainer = document.getElementById("stayCheckboxContainer");
const darkToggle        = document.getElementById("darkModeToggle");